/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#4A6CF7',
        secondary: '#5E72E4',
        'primary-container': '#6E8EF7',
        'primary-fixed': '#DCE4FF',
        'primary-fixed-dim': '#B8C6FF',
        'inverse-primary': '#B8C6FF',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001361',
        'on-primary-fixed-variant': '#1F3AB8',
        'on-primary-container': '#E8EFFF',
        'secondary-container': '#E0E6FF',
        'secondary-fixed': '#E0E8FF',
        'secondary-fixed-dim': '#A8BAFF',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#00125B',
        'on-secondary-fixed-variant': '#1B32A3',
        'on-secondary-container': '#293C8F',
        tertiary: '#9b3e3b',
        'tertiary-container': '#ba5551',
        'tertiary-fixed': '#ffdad7',
        'tertiary-fixed-dim': '#ffb3ae',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#410004',
        'on-tertiary-fixed-variant': '#7f2928',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f7f9ff',
        surface: '#f7f9ff',
        'surface-dim': '#d7dae1',
        'surface-bright': '#f7f9ff',
        'surface-variant': '#dfe2e9',
        'surface-container': '#ebeef5',
        'surface-container-low': '#f1f4fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e5e8ef',
        'surface-container-highest': '#dfe2e9',
        'surface-tint': '#4A6CF7',
        'surface-card': '#FFFFFF',
        'on-surface': '#181c21',
        'on-surface-variant': '#3d4a42',
        'inverse-surface': '#2d3136',
        'inverse-on-surface': '#eef1f8',
        outline: '#6d7a72',
        'outline-variant': '#bccac0',
        'text-main': '#2B3674',
        'text-secondary': '#A3AED0',
        'accent-blue': '#4318FF',
        'status-warning': '#FFB800',
        'status-error': '#EE5D50',
        'status-success': '#059669',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1200px',
        'card-padding': '24px',
        'margin-mobile': '16px',
        gutter: '20px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'display-weight': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-weight': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
      },
      boxShadow: {
        card: 'rgba(163,174,208,0.2) 0px 8px 24px',
        'card-lg': 'rgba(163,174,208,0.1) 0px 20px 40px',
        sidebar: '40px 0 60px -20px rgba(163,174,208,0.2)',
        login: '0 20px 50px rgba(74,108,247,0.2)',
        'glow-primary': '0 0 20px rgba(74,108,247,0.4)',
        'mobile-nav': '0 -4px 12px rgba(0,0,0,0.05)',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-20px) rotate(5deg)' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(0.33)', opacity: '1' },
          '80%, 100%': { opacity: '0' },
        },
        slideIn: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        fadeScale: {
          '0%': { transform: 'scale(0.92)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        'float-d1': 'float 6s ease-in-out 1s infinite',
        'float-d2': 'float 6s ease-in-out 2s infinite',
        'pulse-ring': 'pulse-ring 1.25s cubic-bezier(0.215, 0.61, 0.355, 1) infinite',
        slideIn: 'slideIn 0.25s ease-out',
        fadeScale: 'fadeScale 0.2s ease-out',
      },
    },
  },
  plugins: [],
}
